"""models/comunicacion.py — Comunicacion model (C-12: comunicaciones-cola-worker).

Represents an outbound email communication in the queue. The state machine is:

    Pendiente → Enviando → Enviado
                       └─→ Error
    Pendiente → Cancelado

Design decisions (C-12 design.md):
- destinatario is stored AES-256-GCM encrypted (PII at rest). encrypt/decrypt
  is handled by the service layer, not the model.
- aprobado is a boolean flag: the worker only dispatches aprobado=True messages.
  This decouples the approval concern from the state machine.
- lote_id groups all messages from a single bulk send operation. It is a plain
  UUID generated by the service, not a separate table.
- Soft delete: deleted_at IS NULL means active; never hard DELETE.
- Inherits TenantScopedMixin: id, tenant_id, created_at, updated_at, deleted_at.
"""

import enum
import uuid
from datetime import datetime

from sqlalchemy import Boolean, DateTime, String, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base, TenantScopedMixin


class EstadoComunicacion(str, enum.Enum):
    """State machine for outbound communications (RN-15).

    Valid transitions:
      Pendiente → Enviando → Enviado   (worker dispatches successfully)
      Pendiente → Enviando → Error     (worker dispatch fails)
      Pendiente → Cancelado            (user cancels before dispatch)

    Terminal states (no further transitions): Enviado, Error, Cancelado.
    """

    Pendiente = "Pendiente"
    Enviando = "Enviando"
    Enviado = "Enviado"
    Error = "Error"
    Cancelado = "Cancelado"


# Valid state transitions: {from_state: set_of_allowed_target_states}
VALID_TRANSITIONS: dict[str, set[str]] = {
    "Pendiente": {"Enviando", "Cancelado"},
    "Enviando": {"Enviado", "Error"},
    "Enviado": set(),   # terminal
    "Error": set(),     # terminal
    "Cancelado": set(), # terminal
}


class Comunicacion(Base, TenantScopedMixin):
    """One outbound email communication in the queue.

    Rules:
      - destinatario is AES-256-GCM encrypted; the service layer handles crypto.
      - aprobado=True means the message may be dispatched by the worker.
      - lote_id groups messages from the same bulk send.
      - Soft delete: deleted_at IS NULL means active.
      - estado must follow VALID_TRANSITIONS (enforced by ComunicacionService).
    """

    __tablename__ = "comunicaciones"

    # Note: the composite index (tenant_id, lote_id) is created by migration 0013
    # only. It is not declared here to avoid conflicts with Base.metadata.create_all
    # in tests (which does not support checkfirst on named indexes when the table
    # already exists from a prior test run).
    __table_args__ = ()

    enviado_por: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        nullable=False,
        index=True,
        comment="FK to usuarios.id — the user who triggered the send.",
    )

    materia_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        nullable=True,
        index=True,
        comment="FK to materias.id — context materia for this communication (nullable).",
    )

    destinatario: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="AES-256-GCM encrypted email address of the recipient (PII at rest).",
    )

    asunto: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="Email subject (plaintext, no PII).",
    )

    cuerpo: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="Email body with substitution variables already resolved (plaintext, no PII).",
    )

    estado: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        default="Pendiente",
        server_default="Pendiente",
        comment="State machine value: Pendiente | Enviando | Enviado | Error | Cancelado.",
    )

    aprobado: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=False,
        server_default="FALSE",
        comment=(
            "True when approved for dispatch. The worker only processes "
            "messages where aprobado=True AND estado=Pendiente."
        ),
    )

    lote_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        nullable=False,
        index=True,
        comment="Groups all messages from the same bulk send operation.",
    )

    enviado_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        default=None,
        comment="Timestamp of successful dispatch. NULL until estado=Enviado.",
    )
